version: '3.7'

services:
  db:
    container_name: churraskin-db
    image: mongo:latest
    volumes:
      - churraskin-db-vol
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=guest
      - MONGO_INITDB_ROOT_PASSWORD=guest

volumes:
  churraskin-db-vol: